<?php include 'incs/cabecalho.php'; ?>            
            
            <div id="conteudo">
                <div id="menu">
                     <div id="menu_active">Apresenta&ccedil;&atilde;o</div>
                    <a href="mapas.php" class="menu">Mapas</a><br />
                    <a href="indicadores.php?clrSession=true" class="menu3">Indicadores<br />por Tema</a><br />
                    <a href="metodologia.php" class="menu">Metodologia</a><br />
                    <a href="ficha.php" class="menu">Ficha T&eacute;cnica</a><br />
                </div>
                
                <div id="corpo"><div id="titulo">Avaliação Nacional das Comissões Intergestores Bipartites (CIBs): As CIBs e os modelos de indução da regionalização no SUS </div><br /><br />
                	<p>&nbsp;</p>
                	<p>&nbsp;</p>
                	<p><b>APRESENTAÇÃO</b></p>
<p>A estratégia da regionalização,  apesar de presente nas diretrizes do SUS, como definido pela CF de 1988, só  começa a ser implementada em 2000, quando da edição da NOAS e, de forma mais  incisiva e efetiva, pós Pacto pela Saúde em 2006.<br />
  <br/>O atraso na implementação da  estratégia de regionalização e a ausência de iniciativas combinadas de  descentralização com regionalização requer explicação e a pesquisa <em>Avaliação Nacional das Comissões  Intergestores Bipartites (CIBs): As CIBs e os modelos de indução da  regionalização no SUS</em> aporta algumas questões para essa discussão, na  medida em que identifica o contexto nacional e os fatores condicionantes dos  processos específicos e particulares de regionalização no plano estadual.<br />
  <br/>O objetivo da pesquisa foi mapear  o estado da arte do processo de regionalização e das formas e impactos da  interação entre as CIBs e o processo de regionalização no Brasil, focalizando  as experiências estaduais, de maneira que permitisse comparar diferentes  processos, além de identificar condicionantes institucionais e políticos, e,  ainda, apontar impactos institucionais e inovações introduzidas nos sistemas  estaduais de saúde, a partir da adoção dessa estratégia de política.<br />
  <br/>O processo de regionalização ou a  regionalização na saúde envolve uma mudança no exercício do poder no interior  da política de saúde que se traduz numa redistribuição de poder entre entes governamentais,  agentes, instituições e cidadãos; na criação de novos instrumentos de  integração assistencial, planejamento e gestão; e, por fim, no estabelecimento  de um sistema de inter-relações entre atores, agentes e instituições que pode  ser construída de forma coordenada e cooperativa.<br />
  <br/>A regionalização é um processo  político que pretende conciliar fenômenos quase inconciliáveis, na expressão de  Bifulco<a href="#_ftn1" name="_ftnref1" title="" id="_ftnref1"><sup>1</sup></a>,  como a institucionalização de uma rede homogênea de serviços e intervenções  frente a uma grande heterogeneidade territorial; a formalização da  responsabilidade pública com ampla participação e o envolvimento da sociedade  civil; a regulação centralizada com a manutenção da autonomia dos governos  locais. A questão pode ser assim formulada: como estabelecer um processo de  regionalização que seja ao mesmo tempo eficaz do ponto de vista do  estabelecimento de uma rede homogênea que dê conta das diversidades  territoriais e populacionais, e simultaneamente crie um espaço mais democrático  de decisão da política com a afirmação da responsabilização pública, garantindo  a autonomia local?<br />
  <br/>A resposta para essa intricada  questão só pode ser obtida pela análise dos processos específicos e  particulares de implementação dessa nova estratégia da política de saúde, de  forma a extrair lições e aperfeiçoar os compromissos públicos, includentes e  socialmente justos, dos sistemas nacionais de saúde.</p>
<br/><p><b>MARCO DE ANÁLISE</b></p>
<br/><p>Para a análise do processo de  regionalização foi necessário construir variáveis e indicadores que permitissem  aferir o grau, ritmo e desempenho da implementação dessa estratégia nos  espaços/esferas estaduais, bem como identificar os condicionantes  político-institucionais e os impactos nos sistemas estaduais, nas estruturas e  papel das secretarias e instâncias regionais de saúde e nas formas de  coordenação intergovernamental.<br />
  <br/>Em termos metodológicos foram  selecionados quatro grandes blocos responsáveis pelos rumos da regionalização  ou que condicionam o processo de regionalização, sendo um de natureza nacional  -- o contexto no qual emerge a estratégia da regionalização --, e os demais de  natureza estadual ou local: contexto, imagem-objetivo e processo.<br />
  <br/>Afirma-se com esse procedimento que o  processo de regionalização é variável dependente do contexto mais geral que  informa a política social – uma dada institucionalidade da política -, bem como  é influenciado pelas características específicas da implementação no nível  estadual (institucionalidade e governança do processo de regionalização nos  estados) e, ainda, pelos rumos ou a direção que se deseja imprimir ao processo,  ou seja, a imagem-objetivo definida para a regionalização. <br />
  <br/>Certamente,  outros elementos tais como determinadas variáveis estruturais (a regionalização  se expressa, ou melhor, se materializa em territórios específicos), aferidos  pelas capacidades econômicas, social e do sistema de saúde (capacidade  instalada e complexidade da rede) de cada região também condicionam o processo  de regionalização. Nessa mesma perspectiva, outra variável que condiciona,  ainda, o desempenho da regionalização são os recursos disponíveis para o gasto  público em saúde, que, como se sabe, é altamente dependente da capacidade  arrecadatória própria (observa-se que a evolução do ICMS alinha-se  positivamente com os fluxos da atividade econômica) e das transferências  federais do SUS para os estados. <br />
  <br/>Por fim, a dinâmica dos complexos regionais  em saúde (as relações público-privadas no interior das regiões de saúde) também  influencia o desempenho e os resultados da regionalização no plano estadual e  necessita ser avaliada por estudos de caso específicos, orientados por  referenciais metodológicos apropriados.  <br />
  <br/>A identificação da  institucionalidade da política social e dos fatores que regem ou condicionam o  processo de implementação da regionalização (institucionalidade e governança da  regionalização nos estados), assim como da imagem-objetivo definida pelos  dirigentes estaduais, são essenciais para explicar os condicionantes dos  processos (estaduais) de mudança da política de saúde orientada pela estratégia  da regionalização, bem como o seu avançado ou incipiente estágio de consecução.<br />
  <br/>É necessário também  considerar que esses processos podem ser favorecidos/obstaculizados por um  contexto histórico-estrutural (conformação da regionalização e de estruturas  regionais), político-institucional (histórico da política de saúde) e  conjuntural (tipos de atores e regras políticas de exercício do poder)  específicas e que variam de Estado a Estado.<br />
  <br/>A imagem-objetivo da regionalização expressa  a capacidade dos dirigentes formularem um rumo/orientação ao processo definindo  os atores a serem mobilizados, o objeto do processo de regionalização e,  finalmente, as estratégias e os instrumentos passíveis de auxiliarem o processo  de implementação da regionalização no nível estadual.<br />
  <br/>Uma determinada institucionalidade da  regionalização no plano estadual é conformada pela existência de estratégias,  políticas e projetos direcionados por instituições, compreendendo construções  cognitivas e regras normativas integrantes de processo regulatório que ao mesmo  tempo contém e modela o comportamento social. A institucionalidade de uma  política depende da presença dos três pilares que caracterizam uma instituição:  o regulatório (legitimidade legalmente sancionada), o normativo (obrigação  social, certificação, credenciamento e governança moral) e o cognitivo  (correção conceitual e reconhecimento cultural)<br />
  <br/>A governança da regionalização é determinada  pela capacidade dos atores integrantes da política de construir um quadro  institucional estável que favoreça a cooperação e a participação de uma ampla  gama de atores, marcado pelo estabelecimento de relações cooperativas entre  atores, instituições, agentes e cidadãos, onde é possível estabelecer uma  direção ou rumo voltado para a consecução de metas e objetivos claramente  definidos e acordados.<br />
  <br/>Em suma, a regionalização implica numa  mudança no exercício de poder (redistribuição de poder) no interior da política  de saúde o que se traduz na introdução de novos atores, objeto, normas e  processos, governado/liderado por diferentes orientações/ideologias.<br />
  <br/>Nosso objetivo, portanto, é com base nesse  marco analítico identificar e caracterizar o processo de regionalização na  saúde, apontando seus condicionantes e o contexto no qual ele se desenvolve, de  forma a apreender os limites e desafios dessa estratégia de reforma.<br />
  <br/>Os resultados finais da pesquisa serão  divulgados em material específico e esse site tem com objetivo apenas informar  e disponibilizar  um dos condicionantes  desse processo – o de natureza estrutural - de forma a subsidiar  futuras investigações. </p>
  <BR/>
<br/><p><b>TIPOLOGIA NACIONAL das Comissões Intergestores Regionais (CIRs): condicionantes estruturais  do processo de regionalização</b></p>
<br/><p>O condicionante de natureza estrutural,  referido no marco analítico foi desenhado na forma de uma tipologia nacional  das Comissões Intergestores Regionais (CIRs), com base em indicadores municipais  agregados para cada conjunto de CIRs.<br />
  <br/>Variáveis estruturais, como as  capacidades econômicas, social e do sistema de saúde (capacidade instalada e  complexidade da rede) das regiões compreendidas por cada CIR no Brasil, bem  como suas características demográficas, epidemiológicas e financeiras, além da  disponibilidade de recursos humanos e da presença de centros formadores em seu  interior, diferenciam e, sobretudo, condicionam, as capacidades técnicas, institucionais  e políticas de cada CIR. Da mesma forma, a predominância de equipamentos  públicos e/ou privados também pode interferir nos processos de negociação e  planejamento no interior dessa instância de relacionamento intergovernamental.<br />
  <br/>Aferir e comparar o peso dessas  variáveis, de forma a criar uma tipologia nacional de CIRs foi o intuito desse  trabalho.<br />
  <br/>Para tanto, foram desenvolvidas  metodologias específicas, apresentadas nesse site, de forma a possibilitar  comparações intra e inter estados e regiões. Além disso, os dados e indicadores  foram consolidados em um banco de dados de CIRs, de modo a sistematizar as  informações e permitir o uso corrente desses indicadores por gestores, pesquisadores  e o público em geral.</p>
<div>
  <div id="ftn1"><br />
      <p><a href="#_ftnref1" name="_ftn1" title="" id="_ftn1"> </a> BIFULCO, Lavinia. Strumenti in bilico: il Welfare locale in Italia tra  frammentazione e innovazione. In:  LACOUMES P. e GALÉS, Patrick. Gli strumenti per governare. Italia: Bruno  Mondadori, 2009. </div>
</div>
                </div>
            </div>

<?php require_once("incs/rodape.php"); ?> 